#### Task 3: Import NumPy

This one is easy - just import the package 😄. Make sure to follow the conventions, though!

In [1]:
import numpy as np

#### Task 4: Python vs NumPy

Use pure Python and `numpy` to create a Python list/`numpy`:

- array of $10$ zeros;
- array of $10$ ones;
- array of $10$ fives;
- array of $10$ zeroes, the fifth value of which is $1$;
- array of all the integers from $10$ to $50$;
- array of all the even integers from $10$ to $50$;
- array that is the reversal of the list `[1, 2, 3]` (save these values in an object and use both methods to reverse that object);
- a 3x3 matrix with values ranging from $0$ to $8$;
- a 3x3 identity matrix;
- a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [2]:
zeroes_array = [0 for i in range(0, 10)]
zeroes_array_np = np.zeros(10)
print(
    f"array of 10 zeros \n Python: {zeroes_array} \n Numpy: {zeroes_array_np} \n")

ones_array = [1 for i in range(0, 10)]
ones_array_np = np.ones(10)
print(f"array of 10 ones \n Python: {ones_array} \n Numpy: {ones_array_np} \n")

fives_array = [5 for i in range(0, 10)]
fives_array_np = np.array(fives_array, dtype=float)
print(f"array of 10 fives \n Python: {fives_array} \n Numpy: {fives_array_np} \n")

mixed_array = []
for num in range(0, 10):
    if (num == 4):
        mixed_array.append(1)
    else:
        mixed_array.append(0)
mixed_array_np = np.eye(10)[4]
print(
    f"array of 10 zeroes, the fifth value of which is 1 \n Python: {mixed_array} \n Numpy: {mixed_array_np}\n"
)

nums_array = []
for num in range(10, 50):
    nums_array.append(num)
nums_array_np = np.arange(start=10, stop=51)
print(
    f"array of all the integers from 10 to 50 \n Python: {nums_array} \n Numpy: {nums_array_np}\n"
)

nums_even_array = []
for num in range(10, 51):
    if (num % 2 == 0):
        nums_even_array.append(num)
nums_even_array_np = np.arange(start=10, stop=51, step=2)
print(
    f"array of all the even integers from 10 to 50 \n Python: {nums_even_array} \n Numpy: {nums_even_array_np}\n"
)

array_to_reverse = [1, 2, 3]
reversed_array = list(reversed(array_to_reverse))
reversed_array_np = np.flip(array_to_reverse)
print(
    f"array that is the reversal of the list `[1, 2, 3]` \n Python: {reversed_array} \n Numpy: {reversed_array_np}\n"
)
array_to_reverse = [1, 2, 3]
reversed_array = list(reversed(array_to_reverse))
reversed_array_np = np.flip(array_to_reverse)
print(
    f"array that is the reversal of the list `[1, 2, 3]` \n Python: {reversed_array} \n Numpy: {reversed_array_np}\n"
)

matrix_array = []
for i in range(0, 3):
    row = []
    for j in range(0, 3):
        row.append(i * 3 + j)
    matrix_array.append(row)
matrix_array_np = np.arange(9).reshape(3, 3)
print(
    f"a 3x3 matrix with values ranging from 0 to 8 \n Python: {matrix_array} \n Numpy: {matrix_array_np}\n"
)
id_matrix_array = []
for i in range(0, 3):
    row = []
    for j in range(0, 3):
        row.append(1 if i == j else 0)
    id_matrix_array.append(row)
id_matrix_array_np = np.identity(3)
print(
    f"a 3x3 identity matrix \n Python: {id_matrix_array} \n Numpy: {id_matrix_array_np}\n"
)
diagonal_matrix_array = []
for i in range(0, 5):
    row = []
    for j in range(0, 5):
        row.append(i if i == j + 1 else 0)
    diagonal_matrix_array.append(row)
diagonal_matrix_array_np = np.diag([1,2, 3, 4], k=-1)
print(
    f"a 5x5 matrix with values 1,2,3,4 just below the diagonal \n Python: {diagonal_matrix_array} \n Numpy: {diagonal_matrix_array_np}\n"
)



array of 10 zeros 
 Python: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 
 Numpy: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

array of 10 ones 
 Python: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
 Numpy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

array of 10 fives 
 Python: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5] 
 Numpy: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 

array of 10 zeroes, the fifth value of which is 1 
 Python: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0] 
 Numpy: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

array of all the integers from 10 to 50 
 Python: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49] 
 Numpy: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

array of all the even integers from 10 to 50 
 Python: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50] 
 Numpy: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]



In [ ]:
# Expected result

#### Task 5: Using only NumPy:

1. Create a 5x5 array with $1$ on the border and $0$ inside.
2. Add a border filled with $0$'s on the two sides of an array `[1, 2, 3]`.
3. Create an array of $20$ equally spaced numbers between $0$ and $1$.
4. Create the following matrix:

```text
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

5. Find the indices of the non-zero elements in `[1, 2, 0, 0, 4, 0]`.

In [41]:
ones_zeros_array_np = np.full([5,5], fill_value=0, dtype=float)
ones_zeros_array_np[0, :] = 1
ones_zeros_array_np[-1, :] = 1
ones_zeros_array_np[:, 0] = 1
ones_zeros_array_np[:, -1] = 1
print(
    f"Create a 5x5 array with 1 on the border and 0 inside \n {ones_zeros_array_np}\n"
)

border_array_np = np.arange(start=1, stop=4)
border_array_np = np.pad(border_array_np, 1, mode='constant')
print(
    f"Add a border filled with '0s on the two sides of an array [1, 2, 3] \n {border_array_np}\n"
)

spaced_array_np = np.linspace(0, 1, num=20, endpoint=True)
print(
    f"Create an array of 20 equally spaced numbers between 0 and 1 \n {spaced_array_np}\n"
)

recreation_array_np = np.linspace(0.01, 1, num=100, endpoint=True).reshape(10,10)
print(
    f"Recreation of the matrix \n {recreation_array_np}\n"
)

find_array_np = np.array([1, 2, 0, 0, 4, 0])
find_array_np = list(map(int, np.argwhere(find_array_np > 0).flatten()))
print(
    f"Find the indices of the non-zero elements in [1, 2, 0, 0, 4, 0] \n {find_array_np}\n"
)


Create a 5x5 array with 1 on the border and 0 inside 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Add a border filled with '0s on the two sides of an array [1, 2, 3] 
 [0 1 2 3 0]

Create an array of 20 equally spaced numbers between 0 and 1 
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Recreation of the matrix 
 [[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.8

In [ ]:
# Expected result

Create a 5x5 array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Add a border filled with '0s on the two sides of an array [1, 2, 3]
[0 1 2 3 0]

Create an array of 20 equally spaced numbers between 0 and 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0

#### Task 6: Use NumPy to generate:

- a random number between 0 and 1;
- an array of 25 random numbers sampled from a standard normal distribution;
- a 3x3x3 array with random values drawn from the uniform distribution;
- a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values;
- a random array with values drawn from the uniform distribution of size 30 and find the mean value;
- and multiply a 5x3 matrix by a 3x2 matrix.

**Note**: Your values should be different from the one shown below due to randomness.

In [78]:

random_np = np.random.rand(1)
print(
    f"a random number between 0 and 1 \n {random_np}\n"
)

random_array_np = np.random.randn(25)
print(
    f"an array of 25 random numbers sampled from a standard normal distribution \n {random_array_np}\n"
)

threes_array_np = np.random.uniform(low=0.0, high=1.0, size=(3, 3, 3))
print(
    f"a 3x3x3 array with random values drawn from the uniform distribution \n {threes_array_np}\n"
)

tens_array_np = np.random.uniform(low=0.0, high=1.0, size=(10, 10))
tens_min_max = [np.min(tens_array_np), np.max(tens_array_np)]

print(
    f"a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values \n The array: \n {tens_array_np} \n Min and max values: \n {tens_min_max}"
)

thirties_array_np = np.random.uniform(low=0.0, high=1.0, size=30)
thirties_mean = [np.mean(thirties_array_np)]

print(
    f"a random array with values drawn from the uniform distribution of size 30 and find the mean value \n The array: \n {thirties_array_np} \n Its mean: \n {thirties_mean}"
)

five_three_matrix_np = np.random.uniform(low=0.0, high=1.0, size=(5, 3))
three_two_matrix_np = np.random.uniform(low=0.0, high=1.0, size=(3, 2))
combined_matrix_np = np.dot(five_three_matrix_np, three_two_matrix_np)
print(
    f"multiplying a 5x3 matrix by a 3x2 matrix each with random values \n {combined_matrix_np}\n"
)


a random number between 0 and 1 
 [0.375113]

an array of 25 random numbers sampled from a standard normal distribution 
 [ 0.04958354 -0.04008747 -1.2170637  -0.20441287 -1.12722768  0.02826381
  0.51742979 -2.26085867 -0.6254528   0.26574008  0.2920716  -0.88098565
  0.70443497  0.05699454  0.10305926  1.03502292  0.64782761 -0.27845148
  1.51533636  0.29272542 -0.34931045  0.87429069  0.81768536 -0.00927532
 -0.38954677]

a 3x3x3 array with random values drawn from the uniform distribution 
 [[[0.43030112 0.82638847 0.66657577]
  [0.94879277 0.20641883 0.46083138]
  [0.29455522 0.9064732  0.57526255]]

 [[0.53429245 0.99935759 0.93280043]
  [0.82458001 0.97269608 0.74725135]
  [0.03237638 0.46688702 0.83442914]]

 [[0.95428549 0.90673452 0.57076129]
  [0.25278356 0.72250496 0.81373486]
  [0.16867624 0.83911053 0.36641601]]]

a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values 
 The array: 
 [[0.81017545 0.04281331 0.60877759 0

In [ ]:
# Expected result

a random number between 0 and 1
0.3302392460734943

an array of 25 random numbers sampled from a standard normal distribution
[-0.85565418  0.4592446   0.90183199  0.53932203  0.04080838 -0.4210383
  1.00116207  0.08236895  0.08804113  0.11602095 -0.87912022  0.37818965
 -0.39515241  0.81614267 -0.73406941 -0.49574339 -0.4419727   2.66688758
  1.69571397  0.83054423  1.2732238  -1.55596546 -0.16924736 -1.12509893
 -0.05953329]

a 3x3x3 array with random values drawn from the uniform distribution
[[[0.42054451 0.27312439 0.95347927]
  [0.55134496 0.6235185  0.72550932]
  [0.37674019 0.56769456 0.58315167]]

 [[0.96651862 0.81392441 0.26927728]
  [0.758904   0.75618622 0.35625557]
  [0.12351087 0.43525117 0.68535189]]

 [[0.06672974 0.36402819 0.166292  ]
  [0.95530001 0.84750085 0.25077735]
  [0.95153091 0.8262242  0.86062338]]]

a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values
The array:
[[0.32519229 0.66282593 0.61989954 0.07

#### Task 7: Write code that uses the below matrix to reproduce the expected output

In [79]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
cut_array = []

for i in range(2, len(mat)):
    new_list = []
    for j in range(1, len(mat[i])):
        new_list.append(int(mat[i][j]))
    cut_array.append(new_list)

np.array(cut_array)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# # Expected result
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])

In [93]:
get_twenty = mat[3][-1]

get_twenty

np.int64(20)

In [ ]:
# Expected result

np.int64(20)

In [97]:
three_num_array = []

for i in range(0, 3):
    new_list = [mat[i][1]]
    three_num_array.append(new_list)

np.array(three_num_array)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Expected result

array([[ 2],
       [ 7],
       [12]])

In [99]:
last_row_array = mat[-1]
last_row_array

array([21, 22, 23, 24, 25])

In [ ]:
# Expected result

array([21, 22, 23, 24, 25])

In [106]:
last_two_rows_array = mat[-2:]
last_two_rows_array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected result

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Task 8: Continue using the matrix `mat` to calculate the:

- sum of its values;
- standard deviation of its values;
- the sum of all the columns;

In [ ]:
sum_mat = np.sum(mat)

sum_mat

np.int64(325)

In [ ]:
# Expected result

np.int64(325)

In [109]:
stand_dev_mat = np.std(mat)

stand_dev_mat

np.float64(7.211102550927978)

In [ ]:
# Expected result

np.float64(7.211102550927978)

In [110]:
combined_rows_mat = []

for i in range(0, len(mat)):
    new_sum = 0
    for j in range(0, len(mat[i])):
        new_sum += int(mat[j][i])
    combined_rows_mat.append(new_sum)

np.array(combined_rows_mat)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected result

array([55, 60, 65, 70, 75])

#### Task 9: Let's practice composing operations:

1. Create a 1D array of random integers between $0$ and $9$. Negate all numbers that fall in the interval $[3, 8]$.
2. Create a random array with floating point values of size $10$ and sort it.
3. Create random vector of values drawn from the uniform distribution of size $10$ and replace the maximum value with $0$.

In [201]:
# one_d_array = np.array(list(map(lambda x: x * -1, filter(lambda y: y >= 3 and y <= 8, np.random.randint(0, 10, 10)))))
# res = np.where(np.logical_and(one_d_array >= 3, one_d_array <= 8))
one_d_array = np.random.randint(0, 10, 10)
res = np.where(((one_d_array >= 3) & (one_d_array <= 8)), one_d_array*-1, one_d_array)

res.astype(int)

array([ 9, -4,  1, -6, -6, -7, -6,  9,  9, -8])

In [ ]:
# Expected result

array([-8,  0, -4, -8, -4,  2, -5, -5,  9, -7])

In [156]:
sorted_array = np.sort(np.random.rand(10))
sorted_array


array([0.08420298, 0.17526419, 0.20046117, 0.31707913, 0.33682257,
       0.46981807, 0.52120311, 0.57033256, 0.76576784, 0.91894661])

In [ ]:
# Expected result

array([0.02586911, 0.14107383, 0.38260027, 0.39262931, 0.5819897 ,
       0.68907354, 0.69246722, 0.74188078, 0.77896302, 0.95616985])

In [164]:
random_vector = np.random.uniform(low=0.0, high=1.0, size=10)

print(
    f"The array: {random_vector} \n"
)
random_vector[np.argmax(random_vector)] = 0
print(f"Result: {random_vector}")

The array: [0.97412109 0.2700695  0.15034232 0.88220854 0.2809167  0.5535235
 0.29746234 0.97917802 0.89908465 0.52755284] 

Result: [0.97412109 0.2700695  0.15034232 0.88220854 0.2809167  0.5535235
 0.29746234 0.         0.89908465 0.52755284]


In [ ]:
# Expected result

The array: [0.44451769 0.53691507 0.76973933 0.64541201 0.78163228 0.49481479
 0.38390582 0.04337888 0.16149176 0.22652179]
Result: [0.44451769 0.53691507 0.76973933 0.64541201 0.         0.49481479
 0.38390582 0.04337888 0.16149176 0.22652179]


#### Task 10: Reproducibility

When training models, it's often important to generate the same random numbers every time the application is run, even if the machine changes. This ability helps us remove the possibility of creating the situation: *Well, it works on my machine...*.

Our code should work on all machines and produce the same results across different runs.

Go through the [documentation](https://numpy.org/doc/stable/reference/module_structure.html) and answer the below question.

How can we ensure that we always get the same random numbers (even if we switch machines)? Give two examples.

> **Your answer**: You generate and share a seed, then use it with np.random.default_rng(seed); That way you get the same random numbers, even on different machines.